### ISSUE TITLE
关于前端

### ISSUE THREAD

**Issue by william-song-shy** [SHYOJ-dev/SHYOJ#4]
由于自己写css太费劲了，Bootstrap 又太单调，推荐使用[Semantic UI](https://semantic-ui.com/)或者[Pure](http://purecss.io/)，Bootstrap不是不行，Semantic虽好但是需要Node.JS,不像Pure纯粹CSS

**Comment by william-song-shy** [comment]
大家可以发表一下自己希望用的框架

**Comment by jrjacky** [comment]
额，没啥要求

**Comment by william-song-shy** [comment]
投票呢，得说


---原始邮件---
发件人: &quot;jrjacky&quot;<notifications@github.com&gt;
发送时间: 2020年4月8日(周三) 晚上9:02
收件人: &quot;SHYOJ-dev/SHYOJ&quot;<SHYOJ@noreply.github.com&gt;;
抄送: &quot;Assign&quot;<assign@noreply.github.com&gt;;&quot;william-song-shy&quot;<2560814258@qq.com&gt;;
主题: Re: [SHYOJ-dev/SHYOJ] 关于前端 (#4)




 
额，没啥要求
 
&mdash;

**Comment by william-song-shy** [comment]
补充一下  [semantic的Github地址](https://github.com/semantic-org/semantic-ui/)

**Comment by william-song-shy** [comment]
可以简单地将 Semantic-UI 预编译好的 CSS 和 JavaScript 文件加入到 HTML 的 <head> 元素中，就跟你将 jQuery.min.js 加进去一样。
2. 下载 CSS 和 JS 文件
Semantic-UI 在 GitHub 上的代码仓库里，有准备好的 CSS 和 JS 文件供下载： https://github.com/Semantic-Org/Semantic-UI/tree/master/dist
我们目前需要的是 semantic.min.css 和 semantic.min.js 这两个文件，将它们加入到 HTML 的头部：
```html
<head>
  <link href="./semantic.min.css" rel="stylesheet" type="text/css">
  <script src="./jquery.min.js"></script>
  <script src="./semantic.min.js"></script>
</head>
```
你会发现中间多了一个 jquery.min.js，没错，如果你要使用 Semantic-UI 涉及 JavaScript 的高级功能，比如 tab, progress, sticky, API 等，就必须加上 jQuery 库，这是 Semantic-UI 所需要的全部依赖。

**Comment by william-song-shy** [comment]
<https://zhuanlan.zhihu.com/p/27763751>

**Comment by william-song-shy** [comment]
前端解决，如果想的话，也可以用Bootstrap完成部分内容，但是semantic减少开发量
